spring:
  profiles:
    group:
      local: local-env, common-env
      dev: dev-env, common-env
      stg: stg-env, common-env
      prd: prd-env, common-env
    active: local
---
spring:
  config:
    activate:
      on-profile: common-env

  application:
    name: gateway

  lifecycle:
    timeout-per-shutdown-phase: 10s

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: /data01/ONM/apilog/${spring.application.name}/${spring.application.name}.log
    max-history: 30
    max-size: 30MB
    total-size-cap: 100GB
  pattern:
    console: "%d %-5level [%thread] [traceId:%X{traceId:-}] [spanId:%X{spanId:-}] %logger : %msg%n"
    file: "%d %-5level [%thread] [traceId:%X{traceId:-}] [spanId:%X{spanId:-}] %logger : %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
  level:
    root: INFO
    web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    io.eventuate: INFO
    com.adtcaps.nextoss: TRACE

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "health,mappings"

server:
  shutdown: graceful
---
spring:
  config:
    activate:
      on-profile: local-env

  cloud:
    gateway:
      routes:
#################### 공통 시작
        ##공통관리 (Swagger 허용)
        - id: com-common-api-swagger
          uri: http://localhost:9100
          predicates:
            - Path=/com/common/api-docs, /com/common/api-docs/swagger-config, /com/common/swagger-ui/**, /com/common/swagger-resources/**
        ##계정관리 (Swagger 허용)
        - id: com-account-api-swagger
          uri: http://localhost:9101
          predicates:
            - Path=/com/account/api-docs, /com/account/api-docs/swagger-config, /com/account/swagger-ui/**, /com/account/swagger-resources/**

        ##공통관리
        - id: com-common-api
          uri: http://localhost:9100
          predicates:
            - Path=/api/v1/com/common/**
          filters:
            - LoginAuthFilter
        ##계정관리 (NO 인증 섹션 )
        - id: com-account-api-without-auth
          uri: http://localhost:9101
          predicates:
            - Path=/api/v1/com/account/login
        ##계정관리 (인증필요 섹션 )
        - id: com-account-api
          uri: http://localhost:9101
          predicates:
            - Path=/api/v1/com/account/**
          filters:
            - LoginAuthFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
#             - "*://localhost"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
            exposedHeaders: ["Content-Disposition", "token-status"]
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: "changeme"
      timeout: 30000
      lettuce:
        pool:
          maxTotal: 8
          maxWaitMillis: 10000
          maxIdle: 8
          minIdle: 0

springdoc:
  swagger-ui:
    use-root-path: true
    urls[0]:
      name: account
      url: http://localhost:9102/com/account/swagger-ui/index.html
    urls[1]:
      name: common
      url: http://localhost:9102/com/common/swagger-ui/index.html


server:
  port: 9102

app:
  ip:
    whitelist: 127.0.0.1/32

## JWT Key 값  추후 Secret으로 변경 예정 5분 x 60 x 1000 / 720분 x 60 x 1000
  jwtSecret: adtcapsSecretKey
  jwtExpirationMs: 300000
  jwtRefreshExpirationMs: 43200000

---

spring:
  config:
    activate:
      on-profile: dev-env

---

spring:
  config:
    activate:
      on-profile: stg-env

---

spring:
  config:
    activate:
      on-profile: prd-env


